apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs
provisioner: cvmfs.csi.cern.ch
parameters:
  # Repository address goes here.
  repository: software.eessi.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs  
  namespace: default
  labels:
    ml.azure.com/pvc: "true"
  annotations:
    ml.azure.com/mountpath: "/cvmfs/software.eessi.io"
spec:
  storageClassName: "cvmfs"
  accessModes:
  - ReadOnlyMany      
  resources:
     requests:
       storage: 1
