apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs  
  namespace: default
  labels:
    ml.azure.com/pvc: "true"
  annotations:
    ml.azure.com/mountpath: "/cvmfs"
spec:
  storageClassName: "cvmfs"
  accessModes:
  - ReadOnlyMany      
  resources:
     requests:
       storage: 1
