# ../example/pod-all-repos.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-mount
spec:
  containers:
    - name: demo
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
      volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
          # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
          mountPropagation: HostToContainer
  volumes:
    - name: cvmfs
      persistentVolumeClaim:
        claimName: cvmfs
